---
title: "nldas2_query"
output: 
  html_document:
   keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(janitor)


```


```{r}


daily_indices <- read_rds(file = "data/daily_indices.rds")


# daily_indices <- read_rds(file = "E:/data/daily_indices.rds") %>% 
#   rename(date = `lubridate::date(local_dttm)`) %>% 
#   mutate(wbgt_f_mean = weathermetrics::celsius.to.fahrenheit(wbgt_u_mean),
#          installation = recode(installation, 
#                 `pensacola_nas` = "pensacola",
#                 `portsmouth_nmc` = "portsmouth"))

# write_rds(daily_indices, file = "data/daily_indices.rds")


cc_exposure_df <-
  read_rds(file = "data/cc_exposure_df.rds")

cc_exposure_df <-
  cc_exposure_df %>% 
      mutate(wbgt_mean = weathermetrics::celsius.to.fahrenheit(wbgt_mean),
             wbgt_max = weathermetrics::celsius.to.fahrenheit(wbgt_max))


base_service_df <-
  read_rds(file = "data/base_service_df.rds")



cc_exposure_df %>% 
  count(installation_name) %>% View() #24 installations



# cc_exposure_df <-
#   cc_exposure_df %>% 
#      mutate(installation_name = as_factor(installation_name),
#        installation_name = recode(installation_name,
#         "mcb_camp_lejeune" = "camp_lejeune",
#         "mcb_camp_pendleton" = "camp_pendleton",
#         "fort_benning_ga" = "fort_benning",
#         "fort_sam_houston" = "jbsa",
#         "mcrd_beaufort_parris_island" = "parris_island",
#         "mcb_quantico" = "quantico",
#         "twentynine_palms_main_base" = "twentynine_palms")) 


# write_rds(cc_exposure_df, file = "data/cc_exposure_df.rds")
# write_rds(daily_indices, file = "data/daily_indices.rds")

```


```{r}
daily_indices %>% 
  filter(installation %in% "fort_bliss",
         lubridate::year(date) %in% 2018) %>%
    group_by(lubridate::month(date)) %>% 
  summarise(mean = mean(tmp_f_mean)) 

```



